# Node.js 
FROM node:lts

# 컨테이너의 작업 디렉토리 설정
WORKDIR /usr/src/app

# 현재 디렉토리의 모든 파일을 컨테이너로 복사
COPY . .

# app.js 실행
CMD ["node", "app.js"]

# 이미지 빌드 명령어
# docker build -t my-node .

# 컨테이너 생성 명령어
# docker run --rm my-node