services:
  db:
    container_name: db-container
    image: mysql:8.0
    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306" # "[컨테이너 포트]", 임의의 호스트 포트와 매핑한다.
    networks:
      - db-connect
    # 컨테이너 작동 상태(healthcheck)를 확인한다.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  backend:
    container_name: backend-container
    build:
      context: ./backend
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8080:8080" # "[호스트 포트]:[컨테이너 포트]"
    networks:
      - db-connect
    depends_on:
      # db 컨테이너가 정상 작동(service_healthy) 상태가 될 때 까지 컨테이너 실행을 대기한다.
      db:
        condition: service_healthy

volumes:
  db-volume:

networks:
  db-connect:
