# 베이스 이미지 Node.js 
FROM node:lts

# 작업 폴더 설정
WORKDIR /app

# package.json 복사 및 패키지 설치
COPY package*.json ./
RUN npm install

# 전체 파일 복사
COPY . .

# 포트 명시
EXPOSE 5173

# 서버 실행
CMD ["npm", "run", "dev"]


# 이미지 빌드 
# docker build -t my-react .

# 컨테이너 실행
# docker run --rm -it -p 5173:5173 -v $(pwd):/app -v /app/node_modules my-react
