FROM nginx:stable
COPY ./dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# 이미지 빌드 명령어
# docker build -t nginx-dockerfile .

# 컨테이너 생성 명령어
# docker run -p 80:80 -d nginx-dockerfile